"""init db

Revision ID: 75e3fedbf818
Revises: 
Create Date: 2025-04-17 17:41:04.652429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e3fedbf818'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walletaddress',
    sa.Column('address', sa.String(length=34), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(address) = 34', name='correct_address'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('walletinfo',
    sa.Column('bandwidth', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address'], ['walletaddress.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walletinfo')
    op.drop_table('walletaddress')
    # ### end Alembic commands ###
